name: test

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write # 允许脚本去触发重试工作流


jobs:
  test: 
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Trigger Release Update
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.MY_SECRET_PAT }}
          repository: smallprogram/MyAction
          event-type: openwrt_compilation_completed

      - name: ghcr.io cleanup action
        uses: dataaxiom/ghcr-cleanup-action@v1
        continue-on-error: true
        with:
            delete-untagged: true
            packages: openwrt-base-cache*
            expand-packages: true
            token: ${{ github.token }}