name: test

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write # 允许脚本去触发重试工作流


jobs:
  test: 
    runs-on: ubuntu-latest
    name: test
    steps:

      - name: ghcr.io cleanup action
        uses: dataaxiom/ghcr-cleanup-action@v1
        continue-on-error: true
        with:
            delete-untagged: true
            packages: openwrt-base-cache*
            expand-packages: true
            token: ${{ secrets.MY_SECRET_PAT }}